### ISSUE TITLE
Web interface not available "503 Service Temporarily Unavailable"

### ISSUE THREAD

**Issue by blinklet** [nre-learning/antidote-selfmedicate#23] opened 2019-05-14 19:50 UTC
After cloning the latest version of antidote-selfmedicate and running the script, I see the web interface is unavailable. When I go to the URL http://antidote-local:30001, I see "503 Service Temporarily Unavailable".

I'm using KVM to run the Minikube VM, but I also tried the same with Virtualbox and got the same issue.

$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
antidote-web-57f98b78d4-5wr8l               1/2     Running   0          73m
nginx-ingress-controller-6f575d4f84-m2d5n   1/1     Running   0          73m
syringe-6ffd7b7ccc-6bsxv                    1/1     Running   0          73m

$ kubectl get events
LAST SEEN   TYPE      REASON      KIND   MESSAGE
59m         Normal    Pulled      Pod    Successfully pulled image "antidotelabs/antidote-web:latest"
59m         Normal    Created     Pod    Created container
59m         Normal    Started     Pod    Started container
4m15s       Warning   Unhealthy   Pod    Readiness probe failed: HTTP probe failed with statuscode: 404

$ kubectl logs antidote-web-57f98b78d4-5wr8l antidote-web
14-May-2019 18:37:56.054 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.34
14-May-2019 18:37:56.100 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 4 2018 22:28:22 UTC
14-May-2019 18:37:56.100 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.34.0
14-May-2019 18:37:56.101 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
14-May-2019 18:37:56.101 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0
14-May-2019 18:37:56.101 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
14-May-2019 18:37:56.102 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
14-May-2019 18:37:56.102 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-8u181-b13-2~deb9u1-b13
14-May-2019 18:37:56.102 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
14-May-2019 18:37:56.102 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
14-May-2019 18:37:56.103 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
14-May-2019 18:37:56.120 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
14-May-2019 18:37:56.120 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
14-May-2019 18:37:56.120 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
14-May-2019 18:37:56.206 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
14-May-2019 18:37:56.207 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
14-May-2019 18:37:56.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
14-May-2019 18:37:56.215 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
14-May-2019 18:37:56.216 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
14-May-2019 18:37:56.217 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
14-May-2019 18:37:56.217 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.17] using APR version [1.5.2].
14-May-2019 18:37:56.217 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
14-May-2019 18:37:56.217 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
14-May-2019 18:37:56.281 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0f  25 May 2017]
14-May-2019 18:37:57.479 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
14-May-2019 18:37:57.667 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
14-May-2019 18:37:57.802 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
14-May-2019 18:37:57.813 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
14-May-2019 18:37:57.845 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 6669 ms
14-May-2019 18:37:58.248 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
14-May-2019 18:37:58.253 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.34
14-May-2019 18:37:58.711 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/guacamole.war]
14-May-2019 18:38:19.262 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
18:38:24.829 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/root/.guacamole".
18:38:26.816 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
18:38:30.292 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/root/.guacamole".
18:38:54.185 [localhost-startStop-1] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" loaded.
18:38:54.237 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/root/.guacamole".
18:38:56.122 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
14-May-2019 18:39:01.892 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.RESTExceptionMapper as a provider class
14-May-2019 18:39:01.906 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.extension.ExtensionRESTService as a root resource class
14-May-2019 18:39:01.906 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.language.LanguageRESTService as a root resource class
14-May-2019 18:39:01.906 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.patch.PatchRESTService as a root resource class
14-May-2019 18:39:01.907 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.auth.TokenRESTService as a root resource class
14-May-2019 18:39:01.907 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.session.SessionRESTService as a root resource class
14-May-2019 18:39:01.910 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
14-May-2019 18:39:01.948 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
14-May-2019 18:39:03.252 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.RESTExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton"
14-May-2019 18:39:03.299 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
14-May-2019 18:39:12.237 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.extension.ExtensionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
14-May-2019 18:39:12.281 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
14-May-2019 18:39:12.286 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.patch.PatchRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
14-May-2019 18:39:12.323 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
14-May-2019 18:39:12.361 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.session.SessionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
14-May-2019 18:39:12.602 INFO [localhost-startStop-1] org.webjars.servlet.WebjarsServlet.init WebjarsServlet initialization completed
14-May-2019 18:39:12.851 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/guacamole.war] has finished in [74,140] ms
14-May-2019 18:39:12.855 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
14-May-2019 18:39:15.401 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
14-May-2019 18:39:15.423 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [2,568] ms
14-May-2019 18:39:15.661 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
14-May-2019 18:39:16.055 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
14-May-2019 18:39:16.093 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 78247 ms

$ kubectl logs antidote-web-57f98b78d4-5wr8l guacd
guacd[8]: INFO: Guacamole proxy daemon (guacd) version 1.0.0 started
guacd[8]: INFO: Listening on host 0.0.0.0, port 4822

$ kubectl logs nginx-ingress-controller-6f575d4f84-m2d5n
I0514 18:28:26.825605       1 launch.go:101] &{NGINX 0.9.0-beta.5 git-83cb03b5 git@github.com:ixdy/kubernetes-ingress.git}
I0514 18:28:26.825920       1 launch.go:104] Watching for ingress class: nginx
I0514 18:28:26.826893       1 launch.go:257] Creating API server client for https://10.96.0.1:443
I0514 18:28:27.032937       1 launch.go:120] validated default/antidote-web as the default backend
I0514 18:28:27.522364       1 controller.go:1183] starting Ingress controller
I0514 18:28:27.551295       1 leaderelection.go:203] attempting to acquire leader lease...
I0514 18:28:27.719863       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"syringe-ingress", UID:"35af1048-7675-11e9-892a-0800271a3b81", APIVersion:"extensions", ResourceVersion:"518", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/syringe-ingress
I0514 18:28:27.747215       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"antidote-web-ingress", UID:"3ab6d2c9-7675-11e9-892a-0800271a3b81", APIVersion:"extensions", ResourceVersion:"543", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/antidote-web-ingress
I0514 18:28:28.102244       1 leaderelection.go:213] successfully acquired lease default/ingress-controller-leader-nginx
W0514 18:28:28.567548       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0514 18:28:28.718266       1 queue.go:88] requeuing default/antidote-web-ingress, err deferring sync till endpoints controller has synced
W0514 18:28:29.048185       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:28:29.057273       1 controller.go:842] service default/syringe does not have any active endpoints
W0514 18:28:29.057608       1 controller.go:842] service default/antidote-web does not have any active endpoints
W0514 18:28:36.744125       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:28:36.744158       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:28:36.744190       1 controller.go:556] service default/antidote-web does not have any active endpoints
I0514 18:28:36.753373       1 metrics.go:34] changing prometheus collector from  to default
I0514 18:28:38.027330       1 controller.go:420] ingress backend successfully reloaded...
W0514 18:28:38.029339       1 controller.go:556] service default/antidote-web does not have any active endpoints
...removed many similar logs...
W0514 18:28:40.414313       1 queue.go:88] requeuing default/nginx-ingress, err invalid nginx configuration (empty)
W0514 18:28:41.050397       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:28:41.061131       1 controller.go:842] service default/syringe does not have any active endpoints
W0514 18:28:41.062655       1 controller.go:842] service default/antidote-web does not have any active endpoints
...removed many similar logs...
I0514 18:28:58.361746       1 status.go:302] updating Ingress default/syringe-ingress status to [{ }]
I0514 18:28:58.369534       1 status.go:302] updating Ingress default/antidote-web-ingress status to [{ }]
I0514 18:28:58.450100       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"syringe-ingress", UID:"35af1048-7675-11e9-892a-0800271a3b81", APIVersion:"extensions", ResourceVersion:"1108", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/syringe-ingress
W0514 18:28:58.611089       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist
I0514 18:28:58.634880       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"antidote-web-ingress", UID:"3ab6d2c9-7675-11e9-892a-0800271a3b81", APIVersion:"extensions", ResourceVersion:"1109", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/antidote-web-ingress
W0514 18:28:59.063929       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:28:59.066254       1 controller.go:842] service default/syringe does not have any active endpoints
W0514 18:28:59.069286       1 controller.go:842] service default/antidote-web does not have any active endpoints
...removed many similar logs...
W0514 18:29:08.621429       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist
W0514 18:29:18.623037       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist
W0514 18:29:28.632009       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist
W0514 18:29:38.644427       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist
...removed many similar logs...
W0514 18:32:41.946688       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:32:43.231291       1 queue.go:88] requeuing default/syringe, err
-------------------------------------------------------------------------------
Error: waitid: no child processes
nginx: the configuration file /tmp/nginx-cfg370968901 syntax is ok
nginx: configuration file /tmp/nginx-cfg370968901 test is successful

-------------------------------------------------------------------------------
W0514 18:32:43.286987       1 controller.go:556] service default/antidote-web does not have any active endpoints
W0514 18:32:43.315860       1 controller.go:842] service default/antidote-web does not have any active endpoints
...removed many similar logs...
W0514 19:45:35.020347       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist
W0514 19:45:45.025063       1 backend_ssl.go:54] error obtaining PEM from secret default/: secret named default/ does not exist

**Comment by GaddePradeep** [comment] 2019-05-15 07:23
Hi , ran into the exact same issue on MacOS+VirtualBox, issue#22 .

**Comment by Mierdin** [comment] 2019-05-15 08:29
Closing as a duplicate of #22 - this should be fixed now, please refer to that issue for updates.

**Closed as completed by Mierdin** 2019-05-15 08:29 UTC
