### ISSUE TITLE
Installing on MacOS(Mojave) antidote-web is not getting ready (1/2) because of  Readiness probe failed: HTTP probe failed with statuscode: 404

### ISSUE THREAD

**Issue by GaddePradeep** [nre-learning/antidote-selfmedicate#22] opened 2019-05-11 09:56 UTC
Running the initial set-up on a Mac (MacOS Mojave), I get the following error:sed: 1: "/etc/hosts": extra characters at the end of h command

As its already reported, trying to access manually http://192.168.99.X:30001/ , getting 503 Service Temporarily Unavailable (nginx/1.11.12) .

pradga-mbp:~ pradga$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

pradga-mbp:~ pradga$ minikube version
minikube version: v0.34.1

Every time, antidote-web is not getting ready (1/2) because of  Readiness probe failed: HTTP probe failed with statuscode: 404

pradga-mbp:~ pradga$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
antidote-web-57f98b78d4-l4rnv               1/2     Running   0          113m
nginx-ingress-controller-6f575d4f84-t5c97   1/1     Running   0          113m
syringe-6ffd7b7ccc-t2qhj                    1/1     Running   0          113m

pradga-mbp:~ pradga$ kubectl get deployments
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
antidote-web               0/1     1            0           114m
nginx-ingress-controller   1/1     1            1           114m
syringe                    1/1     1            1           114m

pradga-mbp:~ pradga$ kubectl get service
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
antidote-web    ClusterIP   10.103.193.35   <none>        8080/TCP             114m
kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP              115m
nginx-ingress   NodePort    10.97.117.34    <none>        80:30001/TCP         114m
syringe         ClusterIP   10.108.235.71   <none>        50099/TCP,8086/TCP   114m

pradga-mbp:~ pradga$ kubectl get events
LAST SEEN   TYPE      REASON      KIND   MESSAGE
3m56s       Warning   Unhealthy   Pod    Readiness probe failed: HTTP probe failed with statuscode: 404

**Comment by GaddePradeep** [comment] 2019-05-11 12:38
Not sure if this this related to  "multus" plugin - There are some errors for this.

 ~/antidote-local/antidote-selfmedicate  master kubectl get events
LAST SEEN   TYPE      REASON                    KIND         MESSAGE
15m         Normal    Scheduled                 Pod          Successfully assigned default/antidote-web-57f98b78d4-tvfzf to minikube
15m         Warning   FailedCreatePodSandBox    Pod          Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "543d305ecd832d2b34d020e825e1a0db4252597aa36e5da2e377763e8ae994eb" network for pod "antidote-web-57f98b78d4-tvfzf": NetworkPlugin cni failed to set up pod "antidote-web-57f98b78d4-tvfzf_default" network: failed to find plugin "multus" in path [/opt/cni/bin], failed to clean up sandbox container "543d305ecd832d2b34d020e825e1a0db4252597aa36e5da2e377763e8ae994eb" network for pod "antidote-web-57f98b78d4-tvfzf": NetworkPlugin cni failed to teardown pod "antidote-web-57f98b78d4-tvfzf_default" network: failed to find plugin "multus" in path [/opt/cni/bin]]
15m         Normal    SandboxChanged            Pod          Pod sandbox changed, it will be killed and re-created.
15m         Normal    Pulling                   Pod          pulling image "guacamole/guacd"
13m         Normal    Pulled                    Pod          Successfully pulled image "guacamole/guacd"
13m         Normal    Created                   Pod          Created container
13m         Normal    Started                   Pod          Started container
13m         Normal    Pulling                   Pod          pulling image "antidotelabs/antidote-web:latest"
11m         Normal    Pulled                    Pod          Successfully pulled image "antidotelabs/antidote-web:latest"
11m         Normal    Created                   Pod          Created container
11m         Normal    Started                   Pod          Started container
10m         Warning   Unhealthy                 Pod          Readiness probe failed: Get http://10.32.0.5:8080/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
37s         Warning   Unhealthy                 Pod          Readiness probe failed: HTTP probe failed with statuscode: 404
15m         Normal    SuccessfulCreate          ReplicaSet   Created pod: antidote-web-57f98b78d4-tvfzf
14m         Normal    CREATE                    Ingress      Ingress default/antidote-web-ingress
14m         Normal    UPDATE                    Ingress      Ingress default/antidote-web-ingress
15m         Normal    ScalingReplicaSet         Deployment   Scaled up replica set antidote-web-57f98b78d4 to 1
17m         Normal    NodeHasSufficientMemory   Node         Node minikube status is now: NodeHasSufficientMemory
17m         Normal    NodeHasNoDiskPressure     Node         Node minikube status is now: NodeHasNoDiskPressure
17m         Normal    NodeHasSufficientPID      Node         Node minikube status is now: NodeHasSufficientPID
17m         Normal    RegisteredNode            Node         Node minikube event: Registered Node minikube in Controller
17m         Normal    Starting                  Node         Starting kube-proxy.
15m         Normal    Scheduled                 Pod          Successfully assigned default/nginx-ingress-controller-6f575d4f84-ggsmf to minikube
15m         Warning   FailedCreatePodSandBox    Pod          Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "84a6771d996f53c0b5e42afd0935e63861672924d47361e6222867e512b49ae3" network for pod "nginx-ingress-controller-6f575d4f84-ggsmf": NetworkPlugin cni failed to set up pod "nginx-ingress-controller-6f575d4f84-ggsmf_default" network: failed to find plugin "multus" in path [/opt/cni/bin], failed to clean up sandbox container "84a6771d996f53c0b5e42afd0935e63861672924d47361e6222867e512b49ae3" network for pod "nginx-ingress-controller-6f575d4f84-ggsmf": NetworkPlugin cni failed to teardown pod "nginx-ingress-controller-6f575d4f84-ggsmf_default" network: failed to find plugin "multus" in path [/opt/cni/bin]]
15m         Normal    SandboxChanged            Pod          Pod sandbox changed, it will be killed and re-created.
15m         Normal    Pulling                   Pod          pulling image "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.5"
14m         Normal    Pulled                    Pod          Successfully pulled image "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.5"
14m         Normal    Created                   Pod          Created container
14m         Normal    Started                   Pod          Started container
15m         Normal    SuccessfulCreate          ReplicaSet   Created pod: nginx-ingress-controller-6f575d4f84-ggsmf
16m         Normal    ScalingReplicaSet         Deployment   Scaled up replica set nginx-ingress-controller-6f575d4f84 to 1
15m         Normal    Scheduled                 Pod          Successfully assigned default/syringe-6ffd7b7ccc-xsw9s to minikube
15m         Warning   FailedCreatePodSandBox    Pod          Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "d88ad47d6f0ffc133059e50850052c58c742cfabb0b2103b8ea4039d68ea2958" network for pod "syringe-6ffd7b7ccc-xsw9s": NetworkPlugin cni failed to set up pod "syringe-6ffd7b7ccc-xsw9s_default" network: failed to find plugin "multus" in path [/opt/cni/bin], failed to clean up sandbox container "d88ad47d6f0ffc133059e50850052c58c742cfabb0b2103b8ea4039d68ea2958" network for pod "syringe-6ffd7b7ccc-xsw9s": NetworkPlugin cni failed to teardown pod "syringe-6ffd7b7ccc-xsw9s_default" network: failed to find plugin "multus" in path [/opt/cni/bin]]
15m         Normal    SandboxChanged            Pod          Pod sandbox changed, it will be killed and re-created.
15m         Normal    Pulling                   Pod          pulling image "antidotelabs/syringe:latest"
13m         Normal    Pulled                    Pod          Successfully pulled image "antidotelabs/syringe:latest"
13m         Normal    Created                   Pod          Created container
13m         Normal    Started                   Pod          Started container
15m         Normal    SuccessfulCreate          ReplicaSet   Created pod: syringe-6ffd7b7ccc-xsw9s
14m         Normal    CREATE                    Ingress      Ingress default/syringe-ingress
14m         Normal    UPDATE                    Ingress      Ingress default/syringe-ingress
15m         Normal    ScalingReplicaSet         Deployment   Scaled up replica set syringe-6ffd7b7ccc to 1
 pradga@pradga-mbp  ~/antidote-local/antidote-selfmedicate   master  
 ✘ pradga@pradga-mbp  ~/antidote-local/antidote-selfmedicate   master  


From minikube ssh :



$ ping 10.32.0.5
PING 10.32.0.5 (10.32.0.5): 56 data bytes
64 bytes from 10.32.0.5: seq=0 ttl=64 time=0.262 ms
^C
--- 10.32.0.5 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.262/0.262/0.262 ms

$ curl http://10.32.0.5:8080
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.34</h3></body></html>$

**Comment by Mierdin** [comment] 2019-05-15 08:31
The nightly builds aren't working like I thought they were, so I need to fix that. In the meantime, it appears this was caused by a broken build a while back. I just manually built the latest version of `antidote-web` and pushed it, so if you re-download this image by deleting the `antidote-web.....` pod, it should work.

Please chime back in here and let me know either way, so I know if I can close this issue.

**Comment by GaddePradeep** [comment] 2019-05-15 11:09
Thanks Matt for fixing this - now the antidote-web opens .

 pradga@pradga-mbp ~/antidote-local/antidote-selfmedicate  masterkubectl get deployments
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
antidote-web               1/1     1            1           73m
nginx-ingress-controller   1/1     1            1           73m
syringe                    1/1     1            1           73m

 pradga@pradga-mbp  ~/antidote-local/antidote-selfmedicate  master  kubectl get pods       
NAME                                        READY   STATUS    RESTARTS   AGE
antidote-web-57f98b78d4-n48nb               2/2     Running   2          73m
nginx-ingress-controller-6f575d4f84-bqpnp   1/1     Running   1          73m
syringe-6ffd7b7ccc-tz9cx                    1/1     Running   1          37m

But I stil have the lessons not loaded, its not listing any lessons, may be a different issue.I am checking that and update this thread later.

**Comment by Mierdin** [comment] 2019-05-15 18:05
That's likely a Syringe-side issue. Since the web problem is fixed, I'll close this issue and follow up in your forum thread.

**Closed as completed by Mierdin** 2019-05-15 18:05 UTC
